services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.mainframe.net`)"
      - "traefik.http.routers.portainer.middlewares=tailscale-only@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  backend:
    external: true
